# Fase base com .NET ASP.NET runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 81

# Fase de construção
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia e restaura os pacotes do projeto
COPY ["Dima.Web/Dima.Web.csproj", "Dima.Web/"]
COPY ["Dima.Core/Dima.Core.csproj", "Dima.Core/"]
RUN dotnet restore "./Dima.Web/Dima.Web.csproj"

# Copia o restante dos arquivos e realiza o build
COPY . .
WORKDIR "/src/Dima.Web"
RUN dotnet publish "./Dima.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Fase final para servir a aplicação com Nginx
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

# Remove os arquivos padrão do Nginx
RUN rm -rf ./*

# Copia os arquivos estáticos do Blazor para o Nginx
COPY --from=build /app/publish/wwwroot .

# Copia a configuração customizada do Nginx para o diretório correto
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposição da porta 80
EXPOSE 81

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]
