name: Build Solution

on:
  workflow_call:
    inputs:
      solution-path:
        required: true
        type: string

jobs:
  restore-and-build:
    uses: ./.github/workflows/restore-and-build.yml
    with:
      solution-path: ${{ inputs.solution-path }}
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Test
      run: dotnet test ${{ inputs.solution-path }}
